package in.virit.wwcd.demoviews;

import com.vaadin.flow.component.icon.VaadinIcon;
import com.vaadin.flow.component.markdown.Markdown;
import com.vaadin.flow.router.Route;
import in.virit.wwcd.session.UISession;
import org.vaadin.firitin.appframework.MainLayout;
import org.vaadin.firitin.appframework.MenuItem;

@MenuItem(title = "Execute Java in the browser", icon = VaadinIcon.CODE)
@Route(layout = MainLayout.class)
public class ExecuteJavaInTheBrowserView extends AbstractThing {

    public ExecuteJavaInTheBrowserView() {
        image("/photos/wasm.webp", "WebAssembly opens a door to execute actual programming languages in the browser");
        add(md("""
                Java powers a great deal of the internet's busiest websites. But
                what many Java developers didn't realize is that you *can* run Java inside your browser sandbox too. And
                many other programming languages as well.

                And I'm not talking about [GWT](https://www.gwtproject.org), which **transpiles** Java into JS, but
                actually executing the `bytecode` generated by the `javac` with
                [WebAssembly aka WASM](https://developer.mozilla.org/en-US/docs/WebAssembly). And there are actually
                a couple of options:

                 * GraalVM (experimental, available [in GraalVM 25](https://www.youtube.com/watch?v=Z2SWSIThHXY)). The same ahead-of-time compiler that can build "native binaries"
                   from your bytecode can now compile into WASM instead.
                 * [TeaVM](https://teavm.org), an older separate ahead-of-time compiler. Can output both WASM and JS from bytecode. Stable but some limitations as with GraalVM and GWT.
                 * [CheerpJ](https://cheerpj.com), an actual (OpenJDK based) JRE. JDK is C++, C++ can be compiled to WASM, we can run *anything*
                   in the browser. Swing, regular jar files, old school applets, Minecraft or even your IntelliJ IDEA.

                [Open a separate demo app](https://java-in-browser.dokku1.parttio.org/)

                """));
    }
}